### ISSUE TITLE
timedatectl not working on EMMC - but works on SSD

### ISSUE THREAD

**Issue by azrin1972** [avafinger/bananapi-m64-kodi#5]
Hi @avafinger 

I know this repository is almost 3 years old but I'm still using this as part of my work to collect data. I just found out that some systemd modules are not working if booting from EMMC but it works when booting form SDCARD

**Comment by avafinger** [comment]
> systemd modules are not working if booting from EMMC but it works when booting form SDCARD

Can you disclose which one is not working? 
Use the command line and save it as txt.
I have not updated the image since then...

**Comment by azrin1972** [comment]
I've tried timedatectl and hsotnamectl

but the thing is if I boot using SDCARD everything is fine. only when I transfer them to the EMMC

**Comment by avafinger** [comment]
I can't see a reason for that. Maybe some config files point to SD CARD.
To be able to find what is going on, try to remove the service and re-install it.
https://www.tecmint.com/set-time-timezone-and-synchronize-time-using-timedatectl-command/

Maybe you should use timesyncd instead of timedatectl:
https://wiki.archlinux.org/title/systemd-timesyncd

Check if you have both services running...

**Comment by azrin1972** [comment]
The error that I'm getting is always the time our error

**Comment by avafinger** [comment]
Logs, messages, outputs........?

**Comment by avafinger** [comment]
Interesting read: https://serverfault.com/questions/712928/systemctl-commands-timeout-when-ran-as-root

**Comment by azrin1972** [comment]
> Logs, messages, outputs........?

I will get them soon

I'm working on BPI-F2P right now and struggling to make SSD to EMMC script like you did for BPI-M64.
I'm stuck with copying the boot part of it. :)

**Comment by azrin1972** [comment]
I found root cause of the issue - when I do rsync from SSD to EMMC, I exclude the /var/tmp as I though it was  just a temp file. I just need to create the directory and everything works.
